### PR TITLE
#164829159 Configure codeclimate test coverage

### PR DESCRIPTION
**Pull request by ValerieRono**
**What does this PR do?**
Configure codeclimate 

**Description of tasks to be completed?**
- Add repo to codeclimate
- Add maintainability and test coverage badges to readme
- Add generated test report ID to travis environment variables
- Configure .travis.yml script to send report to codeclimate after test run successfully

**How should this be manually tested?**
- Clone the project: git clone https://github.com/andela/ah-centauri-frontend
- cd into the project folder
- Install dependencies: npm install
- Launch development server: npm start

**Any background context you want to provide?**
N/A

**What are the relevant Pivotal Tracker stories?**
#164829159

**screenshots**
image

### CODE REVIEW

**Review by vino-jasuba — APPROVED** [review]

**Review by Sm0k3s — APPROVED** [review]
Nice work

**Review by Mirriam-Maina — COMMENTED** [review]
@ValerieRono Great work. Kindly format this PR description as described in the example given in the group.

**Review by bl4ck4ndbr0wn — APPROVED** [review]
Great implementation and implementing security by adding keys as environment variables.

**Comment by ValerieRono** [comment]
> @ValerieRono Great work. Kindly format this PR description as described in the example given in the group.

Updated,....

**Comment by Mirriam-Maina** [comment]
Looks good to me @ValerieRono NB: To make the pivotal tracker id a link do this: `[#4567567](add the link to the story between these braces)`

**Pull request merged**
